---
- name: Install and Configure Sliver C2
  hosts: teamserver
  become: true
  vars:
#    operators:
#      - op1
#      - op2
#      - op3
    gpg_public_key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBGBlvl8BEACpoAriv9d1vf9FioSKCrretCZg4RnpjEVNDyy6Y4eFp5dyR9KK
      VJbm8gP4ymgqoTrjwqRp/tSiTB6h/inKnxlgy7It0gsRNRpZCGslPRVIQQBStiTv
      sxQ4qIxebvku/4/dqoSmJzhNg9MzClR8HTO7Iv74jP7gGMD+gebvXwapstBkua66
      N4OPRVyau3FvkD1hZR+XWLBA9ba3Ow7XRA/jl4Mk5LpsqUbFEWbung4oBPKtyriM
      RkiRxOpkR7tAGGlay0kfCt9V6ip5GSb2+Mogk3jeqsD1BryABAlgWznxBbK5StXN
      OXRzAT1TbGeEZ0K8FCXYWHLuakEntVKF2w1VaJ+bJDRLEecuiCmAj1kh9Xx99o5z
      Lbgq+1Vad11Bx+9teOflLqil3H19YZPQIkunlW2ugqlvg9V5bywjh6GzRM0r83Oo
      mY7aA75Teueaf2DX/23y+2UG924B9F2DrpNOfnIOb7ytFjVzDa02lpedF1OH0cv6
      mRObEr0N6vJh223XduZDMk1uLIuVkmX5uVjfR5lWafWedykDMGbOYi4o+sABc9+8
      3THwPKg4aRhwWBnblPKqzo598BP1/D1+GAxyc59nMNwFfOTmU7PIfhx7laG9/zxA
      L1CygInIxZbr++NW4vr0qqbLHwX9fKY3C2iee5Q4N8a51bqXEdoM1R+gUwARAQAB
      tB1TbGl2ZXIgPHNsaXZlckBiaXNob3Bmb3guY29tPokCTgQTAQgAOBYhBA7TkA0p
      bPoCg6TkZn35EkBESQOcBQJgZb5fAhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheA
      AAoJEH35EkBESQOcRr8QAI/b9hSOd80uk+I75NbxMeBk1QPZvA3Zj6wO22V4vj0w
      9WlgwT30I5Zgjcmp+hp/+Mf+ywHzlyFRySVm6X1JYgLBT0GLZJvLBjW1oEdah7NP
      i1snzU3v1aRYXwhj1HdIO4HHCJ/y4hv7S1AIQgCtsZ+tQFAA7e8xvj/dgC5xjl5p
      2xxC+P9ZQTuCbO8WyxTMPt/Z/nnQfRO0og/GGLYrJyPed+w6wcThgEbW79YCG1jb
      +M+MRnGZuuFkG6+J/rPPaj6R+DnDkCria0l5LUuQLTgOgFaLXEhsoGeXF6MjwIIb
      bjL8uf4xmJpudbh1TS1IgriURZQkfypANXGK2O81VOcvrfL+u76Rv96M9BAHbxwZ
      l+iVqXhsYHytV0/E8ouuL3UaX/8QNiD2YSLczHc2htq7yCwo7bNCl5P7kySAjTGM
      mJmlJYD1DfRw8uw1or8EtxxwBVlpzNa5Bpnu6HGh7oFtA1ynGaO+VHngfKSUJkYJ
      7y6ZW9wyWdGiKe5Sdp99ngL5+r9fnUChs3MVSE6Fl/WPobALlh57X51+Q7SENXQZ
      a5mSNRGf4ZaaJnCIo3/PXJcqIjxC2CP5rtab1F9fSttUwWYSBcw7voN2COHfaipJ
      JM5PvcLpyi6K5ZP17kjXkRU+hVWGufEmmakE5Mqr4wfsKcggAF7Oatbll1BpKzb2
      uQINBGBlvl8BEACstG4cNeuYsRuKGinYs3P4X0l/r/Z2gFnwBf3l+X5IQKUxbW/l
      32UMSEPUZCnojp8iHnmnL5N0AXLRi7rGU4coQysVwCd09apFom4WZNHGFfd0u+V/
      zxaJ9Lxn6CVoMR1aQ2WCLSy/q06/T3OY7NE5rimtgPOtW2gXu0NLZD54D4SAdCNr
      GF1iUK1R1AKIiY2R2Orp+yUBdUrFqHX9HyGvSC9eFzNGRBfLuW0P9ygUoyebZRBK
      uT7QONgdduvfwJ7T8qYSHrPotOz/bsqcVEoYXFQ5XR/6WW1wJEeBeqBvhqYpsJaE
      0h1zpzK1z6I5jBolyXdznCvm4OPGErynRIsseOtGrYAPFlMdZEUzrVPxbKQ0LVGH
      bDA+PBgwwktt6wgJImGal8KpIbI6nVChCyLv/Ry7+mW15BFjDx3Mdf7Og4HN1KmZ
      Tync6eEW11sculkC2QWXyrjb+o6bdF/6hNsa4XB2XKPCCMECxrOw5vx3lsau0sot
      3hhMbq+FTRXx/pMNEV9c7JaEB1EkV5UAhHHnieOk4NqlIaib5vU6Z8aBHAEvQ1x/
      t+GUWEOr5zvtmvd+YGeU6egX7yrqzSUjiS613oq/Nn1x9AS+dZuxMr+H/CiCnR1U
      OhrUSywALihikehthAjnZoUml6eDCO9kKss2BTqoNthDTf/WXIRE8bY5gwARAQAB
      iQI2BBgBCAAgFiEEDtOQDSls+gKDpORmffkSQERJA5wFAmBlvl8CGwwACgkQffkS
      QERJA5xjow/+Ou+JjNXrQ2wsa2bhXmF6sW3Fzwuzf3DnjLUU8U5I0rxvweSuVxYT
      uSDw7kj6H/alxPkem/6gUAlasfq70PliH7MrBW36FmGlyFf4rO1qAnLy5w1EIQm3
      9C847b0sd7SivVq0Gx1MN25aZA1w1QLPPOQZhf6EXtkVeMOeHOXvmPjyiOcUdaZH
      QXMkrTbKL2mudqUiUDrptgf9b7gfW7G7RWRuzgy8+JyxAyqpasfHdD9/9vpU9twu
      lT/55TwSWQ0IiorgjfJNtJAVKuZ+73MgPPbH1kmSRcUBEleJOMPZvgCHhs5y3eQS
      p5qUN2kQxNXLtWKVE8j9uGzY0DqO583orjATWj52Kz7SM4uio1ZBVLcJht6YPdBH
      9MkG5o3Yuzif05VBnBp8AUeLNKkW4wlg9VUwdLFuY/6vDSApbU/BSvffx4BvOGha
      2RNzTaiZaiie1Hji3/dsI7dCAfajznuzSmW/fBhDZotKEZr6o1m3OTN4gs3tA/pl
      1IjjARdTpaKqQGDtTu520RC5K7AIQvgIVy4sQN0jBZM5qNkr4Qt+U94A3vqjaRGX
      5UofpRVFFWGP9QQAuIacdTioF05sBcw15WC9ULxi2lV8vBsVjT9zIS4zxfRE8u/G
      DxkLsLOBBZZRXOrgxit+tAqinGJ6N9hOvkUlwTLfJM1tpCEFb/Z786g=
      =lxj2
      -----END PGP PUBLIC KEY BLOCK-----
    server_dir: /root/sliver-server
    sliver_config: /root/.sliver/configs
    operator_config_dir: /root/sliver-operators
    operator_config_dest: "{{ playbook_dir }}/files/"

  tasks:
    ######
    ## Sliver server installation role
    ######

    - name: Create server directory
      become: true
      file:
        path: "{{ server_dir }}"
        state: directory

    - name: Stop sliver-server service if running
      become: true
      systemd:
        name: sliver-server.service
        state: stopped
      ignore_errors: true

    - name: Get latest sliver version
      become: true
      uri:
        url: "https://api.github.com/repos/BishopFox/sliver/releases/latest"
        return_content: yes
      register: latest_sliver_version
      until: latest_sliver_version is succeeded
      retries: 5
      delay: 5

    - name: Download sliver server
      become: true
      get_url:
        url: "https://github.com/BishopFox/sliver/releases/download/{{ latest_sliver_version.json.tag_name }}/sliver-server_linux"
        dest: "{{ server_dir }}/sliver-server_linux_{{ latest_sliver_version.json.tag_name }}"
        mode: "0755"

    - name: Download sliver-server binary signature
      get_url:
        url: "https://github.com/BishopFox/sliver/releases/download/{{ latest_sliver_version.json.tag_name }}/sliver-server_linux.sig"
        dest: "{{ server_dir }}/sliver-server_linux_{{ latest_sliver_version.json.tag_name }}.sig"
        
    - name: Verify Sliver Server Binary Signature
      become: true
      vars:
        sliver_binary_name: "sliver-server_linux_{{ latest_sliver_version.json.tag_name }}"
        sliver_binary_signature_name: "{{ sliver_binary_name }}.sig"
      shell: |
        echo "{{ gpg_public_key }}" | gpg --import
        gpg --verify "{{ server_dir }}/{{ sliver_binary_signature_name }}" "{{ server_dir }}/{{ sliver_binary_name }}"
      register: gpg_verify_result
      changed_when: false
      failed_when: gpg_verify_result.rc not in [0, 1]
      ignore_errors: yes

    - name: Fail if signature verification fails
      fail:
        msg: "Sliver Server Binary signature verification failed. The downloaded binary may have been tampered with."
      when: gpg_verify_result.rc != 0

    - name: Create symlink for sliver-server
      become: true
      file:
        src: "{{ server_dir }}/sliver-server_linux_{{ latest_sliver_version.json.tag_name }}"
        dest: /usr/bin/sliver-server
        state: link

    - name: Create systemd service for sliver-server
      become: true
      copy:
        content: |
          [Unit]
          Description=Sliver Server
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/sliver-server
          Restart=always
          User=root
          Group=root

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/sliver-server.service

    - name: Start sliver-server service
      become: true
      systemd:
        name: sliver-server.service
        state: started
        enabled: yes

    - name: Create operator config directory
      become: true
      file:
        path: "{{ operator_config_dir }}"
        state: directory
        
    - name: Create operator config files
      shell: sliver-server operator --name "{{ item }}" --save "{{ operator_config_dir }}/{{ project | lower }}.{{ item }}.cfg" --lhost 127.0.0.1
      loop: "{{ operator_names.split(',') }}"
      when: operator_names | length > 0
      
    - name: Download operator config files
      fetch:
        src: "{{ operator_config_dir }}/{{ project | lower }}.{{ item }}.cfg"
        dest: "{{ operator_config_dest }}/operators/"
        flat: yes
      loop: "{{ operator_names.split(',') }}"
      when: operator_names | length > 0

    # Update the Sliver configuration file
    - name: Update Sliver Server Config
      become: true
      template:
        src: "{{ playbook_dir }}/files/server.json"
        dest: "{{ sliver_config }}/server.json"

    # Restart Sliver Server after config update
    - name: Restart Sliver Server
      become: true
      systemd:
        name: sliver-server
        state: restarted

  handlers:
    - name: Restart Sliver Server
      service:
        name: sliver-server
        state: restarted
